/**
 * The only environment-specific configuration the app needs. Everything
 * else is discovered from the manifest at runtime. Values are read from
 * Vite env vars so the same build artefact can be promoted from
 * staging -> production on Azure Static Web Apps without a rebuild
 * (Azure SWA supports per-environment app settings injected at request
 * time via /config injection, or you can bake these in at build time —
 * see README "Configuration" section for both options).
 */

// Base URL of the GitHub Pages site that hosts the JSON-LD definition files.
export const DEFINITIONS_BASE_URL: string =
  import.meta.env.VITE_DEFINITIONS_BASE_URL?.replace(/\/$/, "") ??
  "https://gs1-switzerland.github.io/WebOntology";

// Path (relative to DEFINITIONS_BASE_URL) of the catalog manifest that
// indexes every sector/domain/artifact combination. GitHub Pages cannot be
// directory-listed, so this manifest is the single discoverable index the
// SPA relies on. See /manifest.schema.json for the contract, and
// /public/sample-manifest.json for a worked example.
export const MANIFEST_PATH: string =
  import.meta.env.VITE_MANIFEST_PATH ?? "registry/manifest.jsonld";

// Path (relative to DEFINITIONS_BASE_URL) of the GS1 sector codelist.
// Published separately from the manifest because it changes far less
// often (it mirrors the NACE-style Gs1Sector code list) and is reused by
// other GS1 tooling beyond this SPA. If it can't be reached, the app
// falls back to the bundled snapshot in src/config/sectors.ts so a
// transient outage never breaks navigation — see loadSectors() in
// src/lib/registryClient.ts.
export const SECTORS_PATH: string =
  import.meta.env.VITE_SECTORS_PATH ?? "registry/sectors.jsonld";

// Path (relative to DEFINITIONS_BASE_URL) of the GS1 domain codelist —
// human-readable names for each domain slug, analogous to sectors.jsonld.
// Same resilience pattern: falls back to src/config/domains.ts if
// unreachable. Not generated by generate-manifest.mjs — hand-maintained,
// like sectors.jsonld, since it changes rarely.
export const DOMAINS_PATH: string =
  import.meta.env.VITE_DOMAINS_PATH ?? "registry/domains.jsonld";

// Public resolver host used to build canonical / permalink URLs shown in
// the UI (e.g. https://ref.gs1.ch/rail/my_term). This does NOT have
// to be the host the SPA itself is served from — though as of the
// ref.gs1.ch custom domain going live on the Azure Static Web App, it
// now typically is: the same host serves both the human-readable SPA at
// /{domain}/{term} and, at /voc/{domain}/{filename}, the artifact
// identifiers generate-manifest.mjs publishes (see PUBLIC_BASE_URL
// there) — two disjoint path namespaces on the one domain, both handled
// by api/src/functions/resolve.js.
export const RESOLVER_HOST: string =
  import.meta.env.VITE_RESOLVER_HOST ?? "https://ref.gs1.ch";

export const DEFAULT_LANGUAGE = "en";
export const SUPPORTED_LANGUAGES = ["en"] as const;
